# Generated by Django 5.1.4 on 2025-02-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Valor Devido')),
                ('days', models.DateField(verbose_name='Dias em Atraso')),
            ],
            options={
                'verbose_name': 'Divida',
                'verbose_name_plural': 'Dividas',
            },
        ),
    ]
