# Generated by Django 5.1.4 on 2025-03-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagme', '0002_debtors_alter_expense_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtors',
            name='expanse_debtor',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='expanse_debtor', to='pagme.expense', verbose_name='Dívida do usuário'),
            preserve_default=False,
        ),
    ]
