# Generated by Django 5.1.4 on 2025-03-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagme', '0003_debtors_expanse_debtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtors',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apelido'),
        ),
    ]
