# Generated by Django 5.1.4 on 2025-03-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagme', '0004_alter_debtors_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Devido'),
        ),
    ]
