# Generated by Django 5.1.4 on 2025-03-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagme', '0005_alter_expense_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtors',
            name='expanse_debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_debtor', to='pagme.expense', verbose_name='Dívida do usuário'),
        ),
    ]
