# Generated by Django 5.1.4 on 2025-03-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagme', '0006_alter_debtors_expanse_debtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='debtor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pagme.debtors', verbose_name='Devedor'),
            preserve_default=False,
        ),
    ]
