# Generated by Django 5.1.4 on 2025-03-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagme', '0007_expense_debtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtors',
            name='expanse_debtor',
        ),
    ]
