# Generated by Django 5.1.4 on 2025-03-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagme', '0009_debtors_last_payment_date_debtors_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtors',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Está pago?'),
        ),
    ]
